version: '3.9'

services:
  db:
    container_name: ddd-db
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ddd
    volumes:
      - ddd-db:/var/lib/postgresql/data

volumes:
  ddd-db:
    driver: local
